[2023-06-04T08:04:39.789+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: most_popular_movies.process_movies manual__2023-06-04T08:04:35.176575+00:00 [queued]>
[2023-06-04T08:04:39.798+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: most_popular_movies.process_movies manual__2023-06-04T08:04:35.176575+00:00 [queued]>
[2023-06-04T08:04:39.798+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-04T08:04:39.813+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): process_movies> on 2023-06-04 08:04:35.176575+00:00
[2023-06-04T08:04:39.818+0000] {standard_task_runner.py:57} INFO - Started process 210 to run task
[2023-06-04T08:04:39.821+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'most_popular_movies', 'process_movies', 'manual__2023-06-04T08:04:35.176575+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/most_popular_movies.py', '--cfg-path', '/tmp/tmp2px8q4_0']
[2023-06-04T08:04:39.821+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask process_movies
[2023-06-04T08:04:39.857+0000] {task_command.py:410} INFO - Running <TaskInstance: most_popular_movies.process_movies manual__2023-06-04T08:04:35.176575+00:00 [running]> on host 7633a4fabdb3
[2023-06-04T08:04:39.934+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='most_popular_movies' AIRFLOW_CTX_TASK_ID='process_movies' AIRFLOW_CTX_EXECUTION_DATE='2023-06-04T08:04:35.176575+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-04T08:04:35.176575+00:00'
[2023-06-04T08:04:39.941+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/most_popular_movies.py", line 30, in process_movies
    movies_df = _process_movies(movie_dict)
  File "/opt/airflow/dags/helper/web_scrape.py", line 83, in _process_movies
    movies_df = movies_df[['movie_id', 'movie_name', 'movie_rating', 'date']]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['movie_id'] not in index"
[2023-06-04T08:04:39.949+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=most_popular_movies, task_id=process_movies, execution_date=20230604T080435, start_date=20230604T080439, end_date=20230604T080439
[2023-06-04T08:04:39.960+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 51 for task process_movies ("['movie_id'] not in index"; 210)
[2023-06-04T08:04:39.992+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-04T08:04:40.008+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
