[2023-06-04T07:59:18.591+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: most_popular_movies.process_movies manual__2023-06-04T07:59:13.593742+00:00 [queued]>
[2023-06-04T07:59:18.596+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: most_popular_movies.process_movies manual__2023-06-04T07:59:13.593742+00:00 [queued]>
[2023-06-04T07:59:18.596+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-04T07:59:18.606+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): process_movies> on 2023-06-04 07:59:13.593742+00:00
[2023-06-04T07:59:18.611+0000] {standard_task_runner.py:57} INFO - Started process 84 to run task
[2023-06-04T07:59:18.614+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'most_popular_movies', 'process_movies', 'manual__2023-06-04T07:59:13.593742+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/most_popular_movies.py', '--cfg-path', '/tmp/tmpch9s9ewp']
[2023-06-04T07:59:18.614+0000] {standard_task_runner.py:85} INFO - Job 46: Subtask process_movies
[2023-06-04T07:59:18.646+0000] {task_command.py:410} INFO - Running <TaskInstance: most_popular_movies.process_movies manual__2023-06-04T07:59:13.593742+00:00 [running]> on host 7633a4fabdb3
[2023-06-04T07:59:18.716+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='most_popular_movies' AIRFLOW_CTX_TASK_ID='process_movies' AIRFLOW_CTX_EXECUTION_DATE='2023-06-04T07:59:13.593742+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-04T07:59:13.593742+00:00'
[2023-06-04T07:59:18.726+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/most_popular_movies.py", line 30, in process_movies
    movies_df = _process_movies(movie_dict)
  File "/opt/airflow/dags/helper/web_scrape.py", line 80, in _process_movies
    movies_df.to_csv('/opt/airflow/dags/data/most_popular_movies.csv', index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/most_popular_movies.csv'
[2023-06-04T07:59:18.734+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=most_popular_movies, task_id=process_movies, execution_date=20230604T075913, start_date=20230604T075918, end_date=20230604T075918
[2023-06-04T07:59:18.742+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 46 for task process_movies ([Errno 2] No such file or directory: '/opt/airflow/dags/data/most_popular_movies.csv'; 84)
[2023-06-04T07:59:18.786+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-04T07:59:18.804+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
